### ISSUE TITLE
Proposed Projection: Geo Albers USA with Territories

### ISSUE THREAD

**Issue by curran** [d3/d3-geo-projection#195] opened 2020-06-19 15:57 UTC
This projection by @almccon would be amazing to have as part of `d3-geo-projection`.

![image](https://user-images.githubusercontent.com/68416/85153324-0fb04b00-b224-11ea-8492-0c38c979d081.png)

https://observablehq.com/@almccon/u-s-map-with-puerto-rico

**Comment by curran** [comment] 2020-06-19 16:10
Here's a port of that logic to standalone ES6 module: https://github.com/datavis-tech/pleth/blob/4e916c05d7c3375cfdaa00172670c287a15a1205/packages/examples/src/pleth/geoAlbersUsaTerritories.js

![image](https://user-images.githubusercontent.com/68416/85154632-b1846780-b225-11ea-8e5c-7264d6d20eb6.png)

**Comment by Fil** [comment] 2020-06-19 17:40
Isn't it a duplicate of https://github.com/d3/d3-geo/issues/152 ?

**Comment by mbostock** [comment] 2020-06-19 18:49
Yep, duplicate.

**Closed by mbostock** 2020-06-19 18:49 UTC

**Comment by curran** [comment] 2020-06-19 20:26
The distinction here is that it also includes US Virgin Islands, American Samoa, Guam, and Northern Mariana Islands.

**Comment by almccon** [comment] 2020-06-19 20:30
Here's another variant with US Virgin Islands, American Samoa, Guam, and Northern Mariana Islands, but where the Pacific possessions are on the left side of the map. This one seemed to be preferred by most people:

https://observablehq.com/@almccon/u-s-map-with-puerto-rico-us-virgin-islands-american-samoa-gua

![Screen Shot 2020-06-19 at 1 30 33 PM](https://user-images.githubusercontent.com/1212178/85177495-12fe0380-b231-11ea-824d-217496d40fbe.png)

**Comment by armsp** [comment] 2020-06-28 06:13
I downloaded the geoshape json files - one [projected](https://observablehq.com/@mbostock/hispanic-or-latino-origin-by-u-s-county) and another [un-projected](https://observablehq.com/@d3/u-s-map-with-puerto-rico) - from Mike Bostock's example both of which have Puerto Rico.

I am trying to display them in the "albersUsa" projection in Vega or Vega-Lite which uses d3. However I don't see it at all. In the unprojected file, "albersUsa" projection filters Puerto Rico and never displays it. In the projected version there is no map, everything is a giant dark rectangle.

@curran @almccon  Any idea how to get it to display in Vega/Vega-Lite?

I see that there are some js files with Puerto Rico too, how do I get them to replace the native d3 js file responsible for the "albersUsa" projection? Perhaps this technique may help me with displaying Puerto Rico too in "albersUsa" projection.
- https://github.com/datavis-tech/pleth/blob/4e916c05d7c3375cfdaa00172670c287a15a1205/packages/examples/src/pleth/geoAlbersUsaTerritories.js
- https://github.com/stamen/dirty-reprojectors/blob/master/projections/albers-usa-territories.js

**Comment by curran** [comment] 2020-07-01 20:03
@armsp It's not recommended to cross-post like this. I responded over in https://github.com/d3/d3-geo/issues/152
